version: '3'
services:
  postgresql:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - result
      - link-vote-result
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
  result:
    build: ./result
    ports:
      - "8081:8888"
    environment:
      - POSTGRES_HOST=postgresql
    depends_on:
      - postgresql
      - worker
    networks:
      - result
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build: ./worker
    depends_on:
      - postgresql
      - redis
    networks:
      - link-vote-result
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:worker/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  vote:
    build: ./vote
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - vote
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
    networks:
      - vote
      - link-vote-result
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  vote:
  result:
  link-vote-result:
