services:
  postgresql:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - result
      - link-vote-result

  result:
    build: ./result
    ports:
      - "8081:8888"
    environment:
      - POSTGRES_HOST=postgresql
    depends_on:
      - postgresql
      - worker
    networks:
      - result

  worker:
    build: ./worker
    depends_on:
      - postgresql
      - redis
    networks:
      - link-vote-result

  vote:
    build: ./vote
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - vote

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - vote
      - link-vote-result

networks:
  vote:
  result:
  link-vote-result:
